
import type { Metadata } from "next";
// import localFont from "next/font/local";
import { monserrat } from "@/ui/fonts";

import "./globals.css";

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import { ReduxProvider } from "@/redux/provider";
import { getSession } from "next-auth/react";


config.autoAddCss = false



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
   //get session user
   const session = await getSession();
   
  
  return (
    <html lang="en">
      <body className={ `${monserrat.className} min-w-80 min-h-full`}>

       <ReduxProvider session={session}>
        
        {children}
        
       </ReduxProvider>
        
      </body>
    </html>
  );
}
